import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve, sep } from "node:path";
import { pathToFileURL } from "node:url";
import {
  hasAcceptedContractSources,
  loadAcceptedContractWithSources,
} from "../contract/load.js";
import {
  renderContractReviewPage,
  type ContractReviewDocument,
} from "../contract/review-page.js";
import {
  buildScreenReviewModel,
  type ContractReviewScreens,
} from "../contract/screen-review-page.js";
import type { ReviewComparison } from "../contract/review-changes.js";
import { screenSettingsForRepository } from "../contract/screen-catalog.js";
import { ContractValidationError } from "../contract/validate.js";
import { ONBOARDING_AGENT_INSTRUCTION } from "./status.js";

export const TIELINE_REVIEW_PAGE = ".tieline/review.html";

export interface ReviewPageResult {
  path: string;
  bytes: number;
  capabilities: number;
  stories: number;
  acceptance_criteria: number;
  /** Present only when the repository enabled screens and the contract loaded. */
  screens?: {
    screens: number;
    unlinked_screens: number;
    stories_without_screens: number;
  };
  warnings: string[];
}

/**
 * The captures directory as a URL relative to the page, so image `path`
 * locators resolve when the page is opened straight from disk.
 */
function capturesUrl(pagePath: string, capturesDirectory: string): string {
  const relativePath = relative(dirname(pagePath), capturesDirectory);
  if (isAbsolute(relativePath)) {
    return pathToFileURL(capturesDirectory).href.replace(/\/?$/, "/");
  }
  const segments = relativePath.split(sep).filter(Boolean);
  return segments.length === 0
    ? ""
    : `${segments.map(encodeURIComponent).join("/")}/`;
}

/**
 * Renders the browsable contract page. An empty spec renders the onboarding
 * empty state instead of failing, and a spec that no longer validates renders
 * its issues, so the page can be written at any point in the workspace
 * lifecycle without gating on contract health. The page lands at
 * `.tieline/review.html` unless `outputPath` says otherwise; only the default
 * location is added to the workspace's ignore file, because a caller-chosen
 * path is the caller's to manage.
 */
export function writeWorkspaceReviewPage(
  root: string,
  repositoryKey: string,
  specDirectory = ".tieline/spec",
  outputPath?: string,
  comparison?: ReviewComparison
): ReviewPageResult {
  let documents: ContractReviewDocument[] = [];
  let warnings: string[] = [];
  const defaultPath = resolve(root, TIELINE_REVIEW_PAGE);
  const path = outputPath ?? defaultPath;
  let screens: ContractReviewScreens | undefined;
  // An invalid screens layout is refused before the preflight walks the spec
  // directory, which a refused layout could fill with screenshots.
  screenSettingsForRepository(root);
  if (hasAcceptedContractSources(root, specDirectory)) {
    try {
      const loaded = loadAcceptedContractWithSources(root, specDirectory);
      documents = loaded.documents.map((document, index) => ({
        path: loaded.sources[index]!.path,
        document,
      }));
      warnings = loaded.warnings;
      if (loaded.screens && loaded.screenCatalog) {
        screens = {
          catalog: loaded.screens,
          capturesUrl: capturesUrl(
            path,
            loaded.screenCatalog.settings.capturesDirectory
          ),
        };
      }
    } catch (error) {
      if (!(error instanceof ContractValidationError)) throw error;
      warnings = error.issues;
    }
  }
  mkdirSync(dirname(path), { recursive: true });
  const serialized = renderContractReviewPage({
    repositoryKey,
    documents,
    warnings,
    onboardingInstruction: ONBOARDING_AGENT_INSTRUCTION,
    ...(screens ? { screens } : {}),
    ...(comparison ? { comparison } : {}),
  });
  writeFileSync(path, serialized);
  if (path === defaultPath) ensureReviewPageIgnored(root);
  const stories = documents.flatMap(
    (entry) => entry.document.capability.stories
  );
  return {
    path,
    bytes: Buffer.byteLength(serialized),
    capabilities: documents.length,
    stories: stories.length,
    acceptance_criteria: stories.reduce(
      (total, story) => total + story.acceptance_criteria.length,
      0
    ),
    ...(screens ? { screens: screenCoverageSummary(documents, screens) } : {}),
    warnings,
  };
}

function screenCoverageSummary(
  documents: ContractReviewDocument[],
  screens: ContractReviewScreens
): NonNullable<ReviewPageResult["screens"]> {
  const { coverage } = buildScreenReviewModel(
    documents.map(({ document }) => document),
    screens
  );
  return {
    screens: coverage.screens,
    unlinked_screens: coverage.unlinked_screens,
    stories_without_screens: coverage.stories_without_screens.length,
  };
}

/**
 * The page is derived output regenerated by init and compile; committing it
 * would put a large rendered artifact in every contract diff. A nested
 * .tieline/.gitignore keeps the decision local to the workspace. An existing
 * file is left alone — it belongs to the user once it exists.
 */
function ensureReviewPageIgnored(root: string): void {
  const ignorePath = resolve(root, ".tieline", ".gitignore");
  if (existsSync(ignorePath)) return;
  writeFileSync(ignorePath, "review.html\n");
}
