import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  hasAcceptedContractSources,
  loadAcceptedContractWithSources,
} from "../contract/load.js";
import {
  renderContractReviewPage,
  type ContractReviewDocument,
} from "../contract/review-page.js";
import { ContractValidationError } from "../contract/validate.js";
import { ONBOARDING_AGENT_INSTRUCTION } from "./status.js";

export const TIELINE_REVIEW_PAGE = ".tieline/review.html";

export interface ReviewPageResult {
  path: string;
  bytes: number;
  capabilities: number;
  stories: number;
  acceptance_criteria: number;
  warnings: string[];
}

/**
 * Renders the browsable contract page. An empty spec renders the onboarding
 * empty state instead of failing, and a spec that no longer validates renders
 * its issues, so the page can be written at any point in the workspace
 * lifecycle without gating on contract health. The page lands at
 * `.tieline/review.html` unless `outputPath` says otherwise; only the default
 * location is added to the workspace's ignore file, because a caller-chosen
 * path is the caller's to manage.
 */
export function writeWorkspaceReviewPage(
  root: string,
  repositoryKey: string,
  specDirectory = ".tieline/spec",
  outputPath?: string
): ReviewPageResult {
  let documents: ContractReviewDocument[] = [];
  let warnings: string[] = [];
  if (hasAcceptedContractSources(root, specDirectory)) {
    try {
      const loaded = loadAcceptedContractWithSources(root, specDirectory);
      documents = loaded.documents.map((document, index) => ({
        path: loaded.sources[index]!.path,
        document,
      }));
      warnings = loaded.warnings;
    } catch (error) {
      if (!(error instanceof ContractValidationError)) throw error;
      warnings = error.issues;
    }
  }
  const defaultPath = resolve(root, TIELINE_REVIEW_PAGE);
  const path = outputPath ?? defaultPath;
  mkdirSync(dirname(path), { recursive: true });
  const serialized = renderContractReviewPage({
    repositoryKey,
    documents,
    warnings,
    onboardingInstruction: ONBOARDING_AGENT_INSTRUCTION,
  });
  writeFileSync(path, serialized);
  if (path === defaultPath) ensureReviewPageIgnored(root);
  const stories = documents.flatMap(
    (entry) => entry.document.capability.stories
  );
  return {
    path,
    bytes: Buffer.byteLength(serialized),
    capabilities: documents.length,
    stories: stories.length,
    acceptance_criteria: stories.reduce(
      (total, story) => total + story.acceptance_criteria.length,
      0
    ),
    warnings,
  };
}

/**
 * The page is derived output regenerated by init and compile; committing it
 * would put a large rendered artifact in every contract diff. A nested
 * .tieline/.gitignore keeps the decision local to the workspace. An existing
 * file is left alone — it belongs to the user once it exists.
 */
function ensureReviewPageIgnored(root: string): void {
  const ignorePath = resolve(root, ".tieline", ".gitignore");
  if (existsSync(ignorePath)) return;
  writeFileSync(ignorePath, "review.html\n");
}
