import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  hasAcceptedContractSources,
  loadAcceptedContractWithSources,
} from "../contract/load.js";
import {
  renderContractReviewPage,
  type ContractReviewDocument,
} from "../contract/review-page.js";
import { ContractValidationError } from "../contract/validate.js";
import { ONBOARDING_AGENT_PROMPT } from "./status.js";

export const TIELINE_REVIEW_PAGE = ".tieline/review.html";

export interface ReviewPageResult {
  path: string;
  stories: number;
}

/**
 * Renders the browsable contract page. An empty spec renders the onboarding
 * empty state instead of failing, and a spec that no longer validates renders
 * its issues, so the page can be written at any point in the workspace
 * lifecycle without gating on contract health.
 */
export function writeWorkspaceReviewPage(
  root: string,
  repositoryKey: string,
  specDirectory = ".tieline/spec"
): ReviewPageResult {
  let documents: ContractReviewDocument[] = [];
  let warnings: string[] = [];
  if (hasAcceptedContractSources(root, specDirectory)) {
    try {
      const loaded = loadAcceptedContractWithSources(root, specDirectory);
      documents = loaded.documents.map((document, index) => ({
        path: loaded.sources[index]!.path,
        document,
      }));
      warnings = loaded.warnings;
    } catch (error) {
      if (!(error instanceof ContractValidationError)) throw error;
      warnings = error.issues;
    }
  }
  const path = resolve(root, TIELINE_REVIEW_PAGE);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(
    path,
    renderContractReviewPage({
      repositoryKey,
      documents,
      warnings,
      onboardingPrompt: ONBOARDING_AGENT_PROMPT,
    })
  );
  ensureReviewPageIgnored(root);
  return {
    path,
    stories: documents.reduce(
      (total, entry) => total + entry.document.capability.stories.length,
      0
    ),
  };
}

/**
 * The page is derived output regenerated by init and compile; committing it
 * would put a large rendered artifact in every contract diff. A nested
 * .tieline/.gitignore keeps the decision local to the workspace. An existing
 * file is left alone — it belongs to the user once it exists.
 */
function ensureReviewPageIgnored(root: string): void {
  const ignorePath = resolve(root, ".tieline", ".gitignore");
  if (existsSync(ignorePath)) return;
  writeFileSync(ignorePath, "review.html\n");
}
