import { existsSync } from "node:fs";
import { dirname, posix, relative, resolve } from "node:path";
import { wildcardPattern } from "./paths.js";
import type { ScreenSettings, ValidatedScreenCatalog } from "./screen-catalog.js";
import { readBoundedFile } from "./screen-import.js";
import { isSceneTestCandidate, type ScreenSceneScan } from "./screen-scenes.js";

/**
 * Scenes Tieline writes so no one hand-writes a test just to open a page.
 * Every catalogued `page` screen that no other test captures gets one scene in
 * one generated file: it runs the agent-written setup module's `prepare`
 * (sign in, seed data, fill in route parameters), opens the route, and
 * captures it. The tags are written out, so the scan, selection, audit, and
 * `--verify` treat the file like any other scene file. A screen that another
 * test captures leaves the file when it is regenerated, so the two never
 * capture the same screen.
 */

export const GENERATED_SCENE_KINDS = ["page"] as const;

export type GeneratedSceneSkip =
  | { key: string; reason: "has_scene"; files: string[] }
  | { key: string; reason: "not_captured" }
  | { key: string; reason: "route_parameters"; route: string };

export interface GeneratedScenesPlan {
  /** The generated file, repository-relative. */
  file: string;
  content: string;
  scenes: Array<{ key: string; route: string }>;
  skipped: GeneratedSceneSkip[];
}

const ROUTE_PARAMETER = /(^|\/)(:|\*|\[)/;

/** How the generated file imports the setup module: relative, without a `.ts` extension. */
function setupImport(file: string, setup: string): string {
  let path = relative(dirname(file), setup).split("\\").join("/");
  if (!path.startsWith(".")) path = `./${path}`;
  return path.replace(/\.ts$/, "");
}

/**
 * Why the configured file could not hold scenes the rest of Tieline sees, or
 * null: the scan reads tags only from files it treats as tests.
 */
export function generatedScenesFileProblem(settings: ScreenSettings): string | null {
  const generated = settings.capture.generatedScenes;
  if (!generated) return "screens.capture.generated_scenes is not configured";
  const patterns = settings.sceneTests ? settings.sceneTests.map(wildcardPattern) : null;
  if (!isSceneTestCandidate(generated.file, patterns)) {
    return `'${generated.file}' is not a file the test scan reads (${
      settings.sceneTests ? "screens.capture.tests" : "*.spec, *.test, or *.screens scripts"
    }), so its tags would not be seen`;
  }
  if (generated.setup !== null && posix.normalize(generated.setup) === posix.normalize(generated.file)) {
    return "the setup module and the generated file must be different files";
  }
  return null;
}

/**
 * The generated scenes file for the catalog as it stands: one scene per
 * `page` screen that is not marked not captured and that no other file tags.
 * A route with parameters needs the setup module to choose its URL, so
 * without one it is skipped and reported.
 */
export function planGeneratedScenes(input: {
  settings: ScreenSettings;
  catalog: ValidatedScreenCatalog;
  scan: Pick<ScreenSceneScan, "tags">;
}): GeneratedScenesPlan {
  const generated = input.settings.capture.generatedScenes;
  if (!generated) throw new Error("screens.capture.generated_scenes is not configured.");
  const scenes: Array<{ key: string; route: string; title: string; applies_to: unknown }> = [];
  const skipped: GeneratedSceneSkip[] = [];
  const entries = [...input.catalog.screens.values()]
    .map(({ entry }) => entry)
    .filter((entry) => (GENERATED_SCENE_KINDS as readonly string[]).includes(entry.kind))
    .sort((left, right) => left.key.localeCompare(right.key));
  for (const entry of entries) {
    const files = (input.scan.tags.get(entry.key) ?? []).filter((file) => file !== generated.file);
    if (files.length > 0) {
      skipped.push({ key: entry.key, reason: "has_scene", files: [...files] });
    } else if (entry.not_captured) {
      skipped.push({ key: entry.key, reason: "not_captured" });
    } else if (generated.setup === null && ROUTE_PARAMETER.test(entry.route)) {
      skipped.push({ key: entry.key, reason: "route_parameters", route: entry.route });
    } else {
      scenes.push({ key: entry.key, route: entry.route, title: entry.title, applies_to: entry.applies_to ?? null });
    }
  }
  const header = [
    "// Generated by `tieline screens scenes` from the screen catalog: one scene for",
    "// each catalogued page no other test captures. Do not edit it. To capture a",
    "// page differently, write its scene in another file and regenerate; the page",
    "// then leaves this file.",
  ];
  const body =
    scenes.length === 0
      ? ["", "// No catalogued page needs a generated scene."]
      : [
          'import { test } from "@playwright/test";',
          'import { tielinePageScene } from "tieline/playwright";',
          ...(generated.setup !== null
            ? [`import { prepare } from ${JSON.stringify(setupImport(generated.file, generated.setup))};`]
            : []),
          ...scenes.flatMap((scene) => [
            "",
            `test(${JSON.stringify(scene.key)}, { tag: ${JSON.stringify(`@screen:${scene.key}`)} }, async ({ page }) => {`,
            `  await tielinePageScene(page, ${JSON.stringify({
              key: scene.key,
              title: scene.title,
              route: scene.route,
              applies_to: scene.applies_to,
            })}${generated.setup !== null ? ", prepare" : ""});`,
            "});",
          ]),
        ];
  return {
    file: generated.file,
    content: `${[...header, ...body].join("\n")}\n`,
    scenes: scenes.map(({ key, route }) => ({ key, route })),
    skipped,
  };
}

export interface GeneratedScenesStatus {
  /**
   * `stale`: the file is missing or differs from what the catalog generates;
   * `invalid`: the configuration cannot work.
   */
  status: "not_configured" | "current" | "stale" | "invalid";
  file: string | null;
  detail: string | null;
}

/** Whether the generated scenes file on disk is the one the catalog generates now. */
export function generatedScenesStatus(input: {
  repositoryRoot: string;
  settings: ScreenSettings;
  catalog: ValidatedScreenCatalog;
  scan: Pick<ScreenSceneScan, "tags">;
}): GeneratedScenesStatus {
  const generated = input.settings.capture.generatedScenes;
  if (!generated) return { status: "not_configured", file: null, detail: null };
  const problem = generatedScenesFileProblem(input.settings);
  if (problem) return { status: "invalid", file: generated.file, detail: problem };
  const plan = planGeneratedScenes(input);
  const path = resolve(input.repositoryRoot, generated.file);
  if (!existsSync(path)) return { status: "stale", file: generated.file, detail: "the file does not exist" };
  let current: string;
  try {
    current = readBoundedFile(path, GENERATED_SCENES_FILE_BYTES, "generated scenes file").toString("utf8");
  } catch (error) {
    return { status: "invalid", file: generated.file, detail: error instanceof Error ? error.message : String(error) };
  }
  return current === plan.content
    ? { status: "current", file: generated.file, detail: null }
    : { status: "stale", file: generated.file, detail: "it differs from the scenes the catalog generates" };
}

/** Largest generated scenes file read back; far above any catalog's. */
export const GENERATED_SCENES_FILE_BYTES = 4 * 1024 * 1024;
