import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { stringify } from "yaml";
import { runManifestRefresh } from "../../../src/commands/refresh-manifest.js";
import { runCheckCommand } from "../../../src/commands/check.js";
import { runContractCommand } from "../../../src/commands/contract.js";
import { readAuthoredContractAtBase } from "../../../src/contract/authored-snapshot.js";
import { tielineConfigSchema } from "../../../src/tieline/workspace.js";
import { tielineConfigJson } from "../../support/fixtures.js";

const temporary = mkdtempSync(resolve(tmpdir(), "tieline-maintenance-test-"));
const root = resolve(temporary, "repo");
const remote = resolve(temporary, "remote.git");
const git = (cwd: string, args: string[]) => execFileSync("git", args, { cwd, encoding: "utf8", stdio: "pipe" }).trim();
try {
  mkdirSync(root);
  git(temporary, ["init", "--bare", remote]);
  git(root, ["init", "-b", "main"]);
  git(root, ["config", "user.name", "Test"]); git(root, ["config", "user.email", "test@example.invalid"]);
  git(root, ["remote", "add", "origin", remote]);
  mkdirSync(resolve(root, ".tieline/spec"), { recursive: true }); mkdirSync(resolve(root, "src"));
  const config = { ...tielineConfigSchema.parse(JSON.parse(tielineConfigJson({ name: "Fixture", repoName: "fixture", specDirectory: "spec" }))), manifest_mode: "post_merge" };
  writeFileSync(resolve(root, ".tieline/config.json"), JSON.stringify(config));
  writeFileSync(resolve(root, "src/checkout.ts"), "export function checkout(confirmed: boolean) { if (!confirmed) throw new Error('confirm'); return 'charged'; }\n");
  const definition = { version: 1, capability: { key: "BILLING", name: "Billing", description: "Confirmed purchases", stories: [{ key: "BILLING-001", title: "Confirm checkout", actor: "buyer", goal: "confirm", benefit: "avoid unwanted charges", lifecycle: "production", acceptance_criteria: [{ key: "AC-BILLING-001", criterion: "Checkout must require confirmation.", links: [{ relation: "implements", provenance: "authored", target: { kind: "code", repository: "fixture", path: "src/checkout.ts", selector: "function:checkout" } }] }] }] } };
  const specPath = resolve(root, ".tieline/spec/billing.yaml");
  writeFileSync(specPath, stringify(definition));
  git(root, ["add", "."]); git(root, ["commit", "-m", "authored base without generated manifest"]); git(root, ["push", "origin", "main"]);
  const base = git(root, ["rev-parse", "HEAD"]);
  let output = "";
  const io = { write: (message: string) => { output += message; } };
  assert.equal(await runCheckCommand({ repository: root, base, json: true }, io), 0);
  const check = JSON.parse(output);
  assert.equal(check.manifest_current, false);
  assert.equal(check.manifest_publication, "pending");
  assert.equal(check.authored_contract_validated, true);
  output = "";
  assert.equal(await runContractCommand("grade", { repository: root, base, unit: "criterion", scope: "claims", emitScope: true, json: true }, io), 0);
  assert.equal(JSON.parse(output).scoped_criteria, 0, "base YAML avoids false onboarding while publication is pending");
  definition.capability.stories[0]!.acceptance_criteria[0]!.criterion = "Checkout must require confirmation and show a receipt.";
  writeFileSync(specPath, stringify(definition)); output = "";
  assert.equal(await runContractCommand("grade", { repository: root, base, unit: "criterion", scope: "claims", emitScope: true, json: true }, io), 0);
  assert.equal(JSON.parse(output).scoped_criteria, 1, "uncompiled claim edits are reviewed");
  definition.capability.stories[0]!.acceptance_criteria[0]!.links[0]!.target.path = "src/missing.ts";
  writeFileSync(specPath, stringify(definition));
  await assert.rejects(runCheckCommand({ repository: root, base, json: true }, io), /does not exist/);
  git(root, ["restore", ".tieline/spec/billing.yaml"]);
  const restoredSpec = readFileSync(specPath, "utf8");
  writeFileSync(specPath, restoredSpec.replace("function:checkout", "function:missing"));
  output = "";
  assert.equal(await runCheckCommand({ repository: root, base, json: true }, io), 1, "post-merge mode still rejects broken selectors");
  assert.ok(JSON.parse(output).locator_findings.some((finding: { resolution: string }) => finding.resolution === "unresolved"));
  writeFileSync(specPath, restoredSpec);
  const baseline = readAuthoredContractAtBase({ repositoryRoot: root, repositoryKey: "fixture", specDirectory: ".tieline/spec", base });
  assert.equal(baseline?.capabilities[0]!.stories[0]!.acceptance_criteria[0]!.criterion, "Checkout must require confirmation.");
  assert.throws(() => readAuthoredContractAtBase({ repositoryRoot: root, repositoryKey: "fixture", specDirectory: "../outside", base }), /repository-relative/);
  // Local dirt must neither be committed nor erased by the publisher.
  writeFileSync(resolve(root, "notes.txt"), "local work\n");
  writeFileSync(resolve(root, ".git/hooks/post-checkout"), "#!/bin/sh\nprintf changed > src/checkout.ts\nexit 1\n", { mode: 0o755 });
  writeFileSync(resolve(root, ".git/hooks/pre-commit"), "#!/bin/sh\nprintf hook > unauthorized.txt\ngit add unauthorized.txt\nprintf corrupt > .tieline/manifest/BILLING.json\ngit add .tieline/manifest/BILLING.json\n", { mode: 0o755 });
  writeFileSync(resolve(root, ".git/hooks/post-index-change"), "#!/bin/sh\nif test -f .tieline/manifest/BILLING.json; then printf corrupt > .tieline/manifest/BILLING.json; fi\n", { mode: 0o755 });
  output = "";
  assert.equal(await runManifestRefresh({ repository: root, branch: "main" }, io), 0);
  const refreshed = JSON.parse(output);
  assert.equal(refreshed.status, "refreshed"); assert.equal(refreshed.source_commit, base);
  assert.equal(git(root, ["rev-parse", "HEAD"]), base);
  assert.equal(readFileSync(resolve(root, "notes.txt"), "utf8"), "local work\n");
  rmSync(resolve(root, ".git/hooks/pre-commit"));
  rmSync(resolve(root, ".git/hooks/post-checkout"));
  rmSync(resolve(root, ".git/hooks/post-index-change"));
  assert.equal(existsSync(resolve(root, "unauthorized.txt")), false);
  const published = git(remote, ["rev-parse", "main"]);
  assert.equal(JSON.parse(git(remote, ["show", "main:.tieline/manifest/BILLING.json"])).capability.stable_id, "BILLING");
  assert.equal(git(remote, ["rev-parse", "main^"]), base);
  assert.ok(git(remote, ["diff", "--name-only", "main^", "main"]).split("\n").every((path) => path.startsWith(".tieline/manifest/")));
  output = "";
  assert.equal(await runManifestRefresh({ repository: root, branch: "main" }, io), 0);
  assert.equal(JSON.parse(output).status, "unchanged"); assert.equal(git(remote, ["rev-parse", "main"]), published);
  assert.equal(git(root, ["for-each-ref", "refs/tieline-refresh/"]), "");
  assert.equal(git(root, ["worktree", "list", "--porcelain"]).split("worktree ").length - 1, 1);
  await assert.rejects(runManifestRefresh({ repository: root, branch: "--bad" }, io), /Invalid/);
  await assert.rejects(runManifestRefresh({ repository: root, branch: "main", remote: "--upload-pack=bad" }, io), /remote name/);
  writeFileSync(resolve(root, ".git/info/attributes"), ".tieline/manifest/*.json filter=corrupt\n");
  git(root, ["config", "filter.corrupt.clean", "printf corrupt"]);
  await assert.rejects(runManifestRefresh({ repository: root, branch: "main" }, io), /differs from validated compiler output/);
  assert.equal(git(remote, ["rev-parse", "main"]), published);
  rmSync(resolve(root, ".git/info/attributes"));
  git(root, ["config", "--unset", "filter.corrupt.clean"]);
  // Move the remote after advertisement but before receive: the publisher must
  // recompile the competing source, never force-push the obsolete manifest.
  git(root, ["fetch", "origin", "main"]); git(root, ["merge", "--ff-only", "FETCH_HEAD"]);
  writeFileSync(resolve(root, "src/checkout.ts"), "export function checkout(confirmed: boolean) { if (!confirmed) throw new Error('confirm A'); return 'charged'; }\n");
  git(root, ["add", "src/checkout.ts"]); git(root, ["commit", "-m", "source A"]); git(root, ["push", "origin", "main"]);
  writeFileSync(resolve(root, "src/checkout.ts"), "export function checkout(confirmed: boolean) { if (!confirmed) throw new Error('confirm B'); return 'charged'; }\n");
  git(root, ["add", "src/checkout.ts"]); git(root, ["commit", "-m", "source B"]); git(root, ["push", "origin", "HEAD:refs/heads/incoming"]);
  const competing = git(root, ["rev-parse", "HEAD"]);
  const hook = resolve(root, ".git/hooks/pre-push");
  const quote = (value: string) => "'" + value.replaceAll("'", "'\"'\"'") + "'";
  writeFileSync(hook, `#!/bin/sh\nrm -- ${quote(hook)}\ngit --git-dir=${quote(remote)} update-ref refs/heads/main ${quote(competing)}\n`, { mode: 0o755 });
  output = "";
  assert.equal(await runManifestRefresh({ repository: root, branch: "main" }, io), 0);
  assert.equal(JSON.parse(output).attempts, 2);
  assert.equal(JSON.parse(output).source_commit, competing);
  assert.equal(git(remote, ["rev-parse", "main^"]), competing);
  // Failures cannot advance the branch or leave a worktree/ref behind.
  git(root, ["fetch", "origin", "main"]); git(root, ["merge", "--ff-only", "FETCH_HEAD"]);
  writeFileSync(resolve(root, "src/checkout.ts"), "export function checkout(confirmed: boolean) { return confirmed; }\n");
  git(root, ["add", "src/checkout.ts"]); git(root, ["commit", "-m", "new source"]); git(root, ["push", "origin", "main"]);
  const beforeFailure = git(remote, ["rev-parse", "main"]);
  writeFileSync(resolve(remote, "hooks/pre-receive"), "#!/bin/sh\nexit 1\n", { mode: 0o755 });
  await assert.rejects(runManifestRefresh({ repository: root, branch: "main" }, io), /failed after 1 attempt/);
  assert.equal(git(remote, ["rev-parse", "main"]), beforeFailure);
  assert.equal(git(root, ["for-each-ref", "refs/tieline-refresh/"]), "");
  assert.equal(git(root, ["worktree", "list", "--porcelain"]).split("worktree ").length - 1, 1);
  rmSync(resolve(remote, "hooks/pre-receive"));
  writeFileSync(resolve(root, ".tieline/config.json"), JSON.stringify({ ...config, manifest_mode: "committed" }));
  git(root, ["add", ".tieline/config.json"]); git(root, ["commit", "-m", "opt out"]); git(root, ["push", "origin", "main"]);
  await assert.rejects(runManifestRefresh({ repository: root, branch: "main" }, io), /must opt into/);
  output = "";
  assert.equal(await runCheckCommand({ repository: root, base, json: true }, io), 1, "default committed mode still gates stale manifests");
  console.log("manifest maintenance tests passed");
} finally { rmSync(temporary, { recursive: true, force: true }); }
