import assert from "node:assert/strict";
import { readFileSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { runScreensAuditCommand, runScreensScenesCommand } from "../../../src/commands/screens.js";
import { readScreensConfig } from "../../../src/config.js";
import { loadScreenCatalog, screenSettingsForRepository } from "../../../src/contract/screen-catalog.js";
import {
  generatedScenesFileProblem,
  generatedScenesStatus,
  planGeneratedScenes,
} from "../../../src/contract/screen-generated-scenes.js";
import { scanScreenScenes } from "../../../src/contract/screen-scenes.js";
import { openAndCapture, type GeneratedScreen } from "../../../src/playwright/page-scene.cjs";
import { report, test } from "../../support/harness.js";
import { captureIO, createScreensWorkspace, type ScreensWorkspace } from "../../support/screen-fixtures.js";

const workspaces: ScreensWorkspace[] = [];
const GENERATED = "e2e/pages.generated.screens.ts";

const NOTES_YAML = `version: 1
capability: NOTES
screens:
  - key: notes-list
    title: Notes list
    route: /notes
    kind: page
    when: A member opens Notes.
  - key: note-detail
    title: "A note, opened"
    route: /notes/:noteId
    kind: page
    when: A member opens a note.
    applies_to:
      role: [member]
  - key: notes-settings
    title: Notes settings
    route: /notes/settings
    kind: page
    when: A member opens settings.
    not_captured:
      reason: flag-off
      detail: Settings are behind the settings flag.
  - key: notes-about
    title: About "Notes"
    route: /about
    kind: page
    when: Anyone opens About.
  - key: notes-list-empty
    title: Notes list, no notes yet
    route: /notes
    kind: state
    when: A member without notes opens Notes.
`;

function workspace(generated: unknown = { file: GENERATED, setup: "e2e/screens.setup.ts" }): ScreensWorkspace {
  const ws = createScreensWorkspace({
    git: true,
    screens: { enabled: true, capture: generated === null ? {} : { generated_scenes: generated } },
    catalog: {
      ".tieline/screens/NOTES.yaml": NOTES_YAML,
      // An agent-written scene already captures the About page.
      "e2e/about.screens.ts": 'test("about", { tag: "@screen:notes-about" }, async () => {});\n',
    },
  });
  workspaces.push(ws);
  return ws;
}

function planFor(ws: ScreensWorkspace) {
  const settings = screenSettingsForRepository(ws.root)!;
  const { catalog, issues } = loadScreenCatalog(ws.root, settings, new Set(["NOTES", "SHARING"]));
  assert.deepEqual(issues, []);
  const scan = scanScreenScenes(ws.root, settings.sceneTests);
  return { settings, catalog, scan, plan: planGeneratedScenes({ settings, catalog, scan }) };
}

console.log("generated page scenes: configuration and plan");

await test("reads the generated scenes block and refuses patterns", () => {
  assert.equal(readScreensConfig({ screens: { enabled: true } })?.capture.generated_scenes, null);
  assert.deepEqual(
    readScreensConfig({ screens: { enabled: true, capture: { generated_scenes: { file: GENERATED } } } })?.capture
      .generated_scenes,
    { file: GENERATED, setup: null }
  );
  for (const generated of [{ file: "e2e/*.ts" }, { file: "../outside.screens.ts" }, { file: GENERATED, setup: "e2e/*.ts" }, { setup: "x.ts" }]) {
    assert.throws(
      () => readScreensConfig({ screens: { enabled: true, capture: { generated_scenes: generated } } }),
      /screens\.capture\.generated_scenes/,
      JSON.stringify(generated)
    );
  }
});

await test("generates a scene for each page no other test captures, and says why it skips the rest", () => {
  const { plan } = planFor(workspace());
  assert.deepEqual(plan.scenes, [
    { key: "note-detail", route: "/notes/:noteId" },
    { key: "notes-list", route: "/notes" },
  ]);
  assert.deepEqual(plan.skipped, [
    { key: "notes-about", reason: "has_scene", files: ["e2e/about.screens.ts"] },
    { key: "notes-settings", reason: "not_captured" },
  ]);
  assert.equal(
    plan.content,
    [
      "// Generated by `tieline screens scenes` from the screen catalog: one scene for",
      "// each catalogued page no other test captures. Do not edit it. To capture a",
      "// page differently, write its scene in another file and regenerate; the page",
      "// then leaves this file.",
      'import { test } from "@playwright/test";',
      'import { tielinePageScene } from "tieline/playwright";',
      'import { prepare } from "./screens.setup";',
      "",
      'test("note-detail", { tag: "@screen:note-detail" }, async ({ page }) => {',
      '  await tielinePageScene(page, {"key":"note-detail","title":"A note, opened","route":"/notes/:noteId","applies_to":{"role":["member"]}}, prepare);',
      "});",
      "",
      'test("notes-list", { tag: "@screen:notes-list" }, async ({ page }) => {',
      '  await tielinePageScene(page, {"key":"notes-list","title":"Notes list","route":"/notes","applies_to":null}, prepare);',
      "});",
      "",
    ].join("\n")
  );
});

await test("without a setup module, skips routes with parameters and imports nothing extra", () => {
  const { plan } = planFor(workspace({ file: GENERATED }));
  assert.deepEqual(plan.scenes, [{ key: "notes-list", route: "/notes" }]);
  assert.ok(plan.skipped.some((skip) => skip.reason === "route_parameters" && skip.key === "note-detail"));
  assert.doesNotMatch(plan.content, /import \{ prepare \}/);
  assert.match(plan.content, /tielinePageScene\(page, \{[^}]*"applies_to":null\}\);/);
});

await test("imports the setup module by its path relative to the generated file", () => {
  for (const [file, setup, expected] of [
    ["e2e/generated/pages.screens.ts", "e2e/support/screens.setup.ts", "../support/screens.setup"],
    ["e2e/pages.screens.mjs", "e2e/screens.setup.mjs", "./screens.setup.mjs"],
  ] as const) {
    const { plan } = planFor(workspace({ file, setup }));
    assert.match(plan.content, new RegExp(`import \\{ prepare \\} from "${expected.replace(/[./]/g, "\\$&")}";`), file);
  }
});

await test("refuses a file the test scan would not read, or a setup module that is the same file", () => {
  const unscanned = screenSettingsForRepository(workspace({ file: "e2e/pages.ts" }).root)!;
  assert.match(generatedScenesFileProblem(unscanned)!, /'e2e\/pages\.ts' is not a file the test scan reads/);
  const same = screenSettingsForRepository(workspace({ file: GENERATED, setup: GENERATED }).root)!;
  assert.match(generatedScenesFileProblem(same)!, /must be different files/);
  const off = screenSettingsForRepository(workspace(null).root)!;
  assert.match(generatedScenesFileProblem(off)!, /not configured/);
});

console.log("generated page scenes: command and audit");

await test("writes the file, keeps it when nothing changed, and --check reports whether it is current", () => {
  const ws = workspace();
  const first = captureIO();
  assert.equal(runScreensScenesCommand({ repository: ws.root }, first.io), 0);
  assert.match(first.output(), /^Created e2e\/pages\.generated\.screens\.ts: 2 generated page scene\(s\); 1 page\(s\) captured by another test, 1 marked not captured\.\n$/);
  const written = readFileSync(`${ws.root}/${GENERATED}`, "utf8");
  assert.equal(written, planFor(ws).plan.content);

  const again = captureIO();
  assert.equal(runScreensScenesCommand({ repository: ws.root, json: true }, again.io), 0);
  assert.equal((JSON.parse(again.output()) as { status: string }).status, "unchanged");

  const current = captureIO();
  assert.equal(runScreensScenesCommand({ repository: ws.root, check: true }, current.io), 0);
  assert.match(current.output(), /is current: 2 generated page scene\(s\)/);

  // An agent writes its own scene for the notes list: the generated one must go.
  ws.write("e2e/notes.screens.ts", 'test("list", { tag: "@screen:notes-list" }, async () => {});\n');
  const stale = captureIO();
  assert.equal(runScreensScenesCommand({ repository: ws.root, check: true }, stale.io), 1);
  assert.match(stale.output(), /out of date with the catalog; run `tieline screens scenes`/);
  assert.equal(readFileSync(`${ws.root}/${GENERATED}`, "utf8"), written, "--check writes nothing");
  assert.equal(runScreensScenesCommand({ repository: ws.root }, captureIO().io), 0);
  assert.doesNotMatch(readFileSync(`${ws.root}/${GENERATED}`, "utf8"), /@screen:notes-list/);
});

await test("refuses to write through a link out of the repository", () => {
  const ws = workspace({ file: "linked/pages.screens.ts" });
  symlinkSync(tmpdir(), `${ws.root}/linked`);
  assert.throws(() => runScreensScenesCommand({ repository: ws.root }, captureIO().io), /outside the repository; nothing was generated/);
});

await test("fails the strict audit while the generated file is missing or stale, and passes it once current", async () => {
  const ws = workspace();
  const settings = screenSettingsForRepository(ws.root)!;
  const { catalog } = loadScreenCatalog(ws.root, settings, new Set(["NOTES", "SHARING"]));
  const scan = scanScreenScenes(ws.root, settings.sceneTests);
  assert.deepEqual(generatedScenesStatus({ repositoryRoot: ws.root, settings, catalog, scan }), {
    status: "stale",
    file: GENERATED,
    detail: "the file does not exist",
  });
  const missing = captureIO();
  assert.equal(await runScreensAuditCommand({ repository: ws.root, strict: true }, missing.io), 1);
  assert.match(missing.output(), /scenes    e2e\/pages\.generated\.screens\.ts: the file does not exist; run `tieline screens scenes`/);
  assert.match(missing.output(), /the generated page scenes are out of date \(the file does not exist\); run `tieline screens scenes`/);

  runScreensScenesCommand({ repository: ws.root }, captureIO().io);
  const after = captureIO();
  await runScreensAuditCommand({ repository: ws.root, strict: true, json: true }, after.io);
  const audit = JSON.parse(after.output()) as { generated_scenes: { status: string }; strict: { failures: string[] } };
  assert.equal(audit.generated_scenes.status, "current");
  assert.ok(!audit.strict.failures.some((failure) => /generated page scenes/.test(failure)));
});

console.log("generated page scenes: the scene body");

function fakePage(status = 200) {
  const visited: string[] = [];
  return {
    visited,
    page: {
      async goto(url: string) {
        visited.push(url);
        return { ok: () => status < 400, status: () => status };
      },
    },
  };
}

const NOTE: GeneratedScreen = { key: "note-detail", title: "A note", route: "/notes/:noteId", applies_to: { role: ["member"] } };

await test("prepares the page, opens the URL it returns, and captures the screen", async () => {
  const { page, visited } = fakePage();
  const captured: string[] = [];
  const prepared: Array<{ key: string; role: readonly string[] | undefined }> = [];
  await openAndCapture(
    page,
    NOTE,
    async (_page, screen) => {
      prepared.push({ key: screen.key, role: screen.applies_to?.role });
      return "/notes/note-1";
    },
    async (_page, key) => {
      captured.push(key);
    }
  );
  assert.deepEqual(prepared, [{ key: "note-detail", role: ["member"] }]);
  assert.deepEqual(visited, ["/notes/note-1"]);
  assert.deepEqual(captured, ["note-detail"]);

  const plain = fakePage();
  await openAndCapture(plain.page, { ...NOTE, route: "/notes" }, undefined, async () => undefined);
  assert.deepEqual(plain.visited, ["/notes"], "without a setup module the catalogued route is opened");
});

await test("refuses a route left with parameters and a page that answers with an error", async () => {
  const unvisited = fakePage();
  await assert.rejects(
    openAndCapture(unvisited.page, NOTE, async () => undefined, async () => undefined),
    /route \/notes\/:noteId, which has parameters: return the URL to open from prepare\(\)/
  );
  assert.deepEqual(unvisited.visited, []);
  for (const route of ["/files/*", "/notes/[noteId]"]) {
    await assert.rejects(openAndCapture(fakePage().page, { ...NOTE, route }, undefined, async () => undefined), /has parameters/);
  }
  const captured: string[] = [];
  await assert.rejects(
    openAndCapture(fakePage(404).page, { ...NOTE, route: "/missing" }, undefined, async (_page, key) => {
      captured.push(key);
    }),
    /\/missing answered HTTP 404, so it was not captured/
  );
  assert.deepEqual(captured, [], "an error page is never captured as the screen");
});

for (const ws of workspaces) ws.cleanup();
report();
