import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { runCodeTopologyArtifactCommand } from "../src/commands/code-topology-artifact.js";
import { runContractCommand } from "../src/commands/contract.js";
import {
  CODE_TOPOLOGY_ARTIFACT_FILE,
  parseCodeTopologyArtifact,
  serializeCodeTopologyArtifact,
} from "../src/contract/code-topology-artifact.js";
import { readWorkspaceCodeTopologyFiles } from "../src/contract/topology-role-snapshot.js";
import { codeTopologyArtifactProjectionDigest } from "../src/domain/code-topology-artifact.js";
import type { TielineCliIO } from "../src/cli.js";
import {
  compareGeneratedArtifact,
  runGeneratedArtifactGate,
  type GeneratedArtifactMismatch,
} from "./generated-artifact-gate.js";
import { tielineConfigJson } from "./lib/fixtures.js";
import { report, test } from "./lib/harness.js";

console.log("Generated artifact derivation gate");

const root = mkdtempSync(resolve(tmpdir(), "tieline-generated-artifacts-"));
try {
  const reviewed = resolve(root, "reviewed");
  const generated = resolve(root, "generated");
  mkdirSync(resolve(reviewed, "nested"), { recursive: true });
  mkdirSync(resolve(generated, "nested"), { recursive: true });
  writeFileSync(resolve(reviewed, "same.json"), "{\"same\":true}\n");
  writeFileSync(resolve(generated, "same.json"), "{\"same\":true}\n");

  await test("identical complete file sets and canonical bytes match", () => {
    assert.equal(compareGeneratedArtifact("manifest", reviewed, generated), null);
  });

  await test("file-set and byte drift identifies the relevant artifact", () => {
    writeFileSync(resolve(reviewed, "reviewed-only.json"), "{}\n");
    writeFileSync(resolve(reviewed, "nested/changed.json"), "{\"value\":1}\n");
    writeFileSync(resolve(generated, "generated-only.json"), "{}\n");
    writeFileSync(resolve(generated, "nested/changed.json"), "{\"value\":2}\n");
    const mismatch = compareGeneratedArtifact("manifest", reviewed, generated);
    assert.deepEqual(mismatch, {
      artifact: "manifest",
      missing_files: ["generated-only.json"],
      unexpected_files: ["reviewed-only.json"],
      changed_files: ["nested/changed.json"],
    } satisfies GeneratedArtifactMismatch);
  });

  await test("a missing reviewed authority is a structured mismatch", () => {
    assert.deepEqual(
      compareGeneratedArtifact("topology", resolve(root, "missing"), generated),
      {
        artifact: "topology",
        missing_files: ["generated-only.json", "nested/changed.json", "same.json"],
        unexpected_files: [],
        changed_files: [],
      } satisfies GeneratedArtifactMismatch
    );
  });

  const fixture = resolve(root, "repository");
  mkdirSync(resolve(fixture, ".tieline/spec"), { recursive: true });
  mkdirSync(resolve(fixture, "src"), { recursive: true });
  writeFileSync(
    resolve(fixture, ".tieline/config.json"),
    tielineConfigJson({
      name: "Derivation fixture",
      repoName: "derivation-fixture",
      specDirectory: "spec",
    })
  );
  const sourcePath = resolve(fixture, "src/value.ts");
  const source = "export function value() { return 1; }\n";
  writeFileSync(sourcePath, source);
  const specPath = resolve(fixture, ".tieline/spec/fixture.yaml");
  const spec = `version: 1
capability:
  key: DERIVATION
  name: Derivation gate
  description: Generated artifacts stay tied to reviewed inputs.
  stories:
    - key: DERIVATION-001
      title: Compare compiler output
      actor: reviewing agent
      goal: detect generated artifact drift
      benefit: reviewed bytes stay authoritative
      lifecycle: production
      acceptance_criteria:
        - key: DERIVATION-001-AC1
          criterion: The gate must compare generated bytes with reviewed bytes.
          links:
            - relation: implements
              provenance: authored
              target:
                kind: code
                repository: derivation-fixture
                path: src/value.ts
                selector: function:value
`;
  writeFileSync(specPath, spec);
  execFileSync("git", ["init", "-q", fixture]);

  const commandOutput: string[] = [];
  const commandIo: TielineCliIO = {
    write(message) {
      commandOutput.push(message);
    },
    error(message) {
      throw new Error(message);
    },
    async question() {
      throw new Error("Derivation tests must not prompt.");
    },
  };
  assert.equal(
    await runContractCommand(
      "compile",
      { repository: fixture, json: true },
      commandIo
    ),
    0
  );
  assert.equal(
    await runCodeTopologyArtifactCommand(
      "compile",
      { repository: fixture, json: true },
      commandIo
    ),
    0,
    commandOutput.at(-1)
  );
  execFileSync("git", ["-C", fixture, "add", "."]);

  await test("isolated compilation, comparison, and artifact-first smoke pass", async () => {
    assert.deepEqual(await runGeneratedArtifactGate(fixture), {
      status: "current",
      artifacts: ["manifest", "topology"],
      trace_status: "complete",
      blast_radius_status: "complete",
      checkout_unchanged: true,
    });
  });

  await test("source, resolver, and spec drift name the affected artifact", async () => {
    writeFileSync(sourcePath, `${source}// source drift\n`);
    let result = await runGeneratedArtifactGate(fixture);
    assert.equal(result.status, "generated_artifact_mismatch");
    assert.ok(
      result.status === "generated_artifact_mismatch" &&
        result.artifacts.some((entry) => entry.artifact === "topology")
    );
    assert.equal(
      result.status === "generated_artifact_mismatch" &&
        result.checkout_unchanged,
      true,
      "failure paths also prove the reviewed checkout stayed byte-identical"
    );
    writeFileSync(sourcePath, source);

    writeFileSync(resolve(fixture, "tsconfig.json"), "{\"compilerOptions\":{\"module\":\"NodeNext\"}}\n");
    result = await runGeneratedArtifactGate(fixture);
    assert.equal(result.status, "generated_artifact_mismatch");
    assert.ok(
      result.status === "generated_artifact_mismatch" &&
        result.artifacts.some((entry) => entry.artifact === "topology")
    );
    rmSync(resolve(fixture, "tsconfig.json"));

    writeFileSync(specPath, spec.replace("reviewed bytes", "canonical reviewed bytes"));
    result = await runGeneratedArtifactGate(fixture);
    assert.equal(result.status, "generated_artifact_mismatch");
    assert.ok(
      result.status === "generated_artifact_mismatch" &&
        result.artifacts.some((entry) => entry.artifact === "manifest")
    );
    assert.deepEqual(
      result.status === "generated_artifact_mismatch"
        ? result.artifacts.map((entry) => entry.artifact)
        : [],
      ["manifest"],
      "intent-only drift leaves the topology compiler output unchanged"
    );
    writeFileSync(specPath, spec);
  });

  await test("producer and committed-byte tampering name topology", async () => {
    const graphPath = resolve(fixture, ".tieline/topology", CODE_TOPOLOGY_ARTIFACT_FILE);
    const graphBytes = readFileSync(graphPath);
    const graph = JSON.parse(graphBytes.toString("utf8"));
    graph.producer.version += 1;
    writeFileSync(graphPath, `${JSON.stringify(graph)}\n`);
    let result = await runGeneratedArtifactGate(fixture);
    assert.equal(result.status, "generated_artifact_mismatch");
    assert.ok(
      result.status === "generated_artifact_mismatch" &&
        result.artifacts.some((entry) => entry.artifact === "topology")
    );
    writeFileSync(graphPath, graphBytes);

    const topology = readWorkspaceCodeTopologyFiles(fixture);
    assert.equal(topology.status, "complete");
    if (topology.status !== "complete") return;
    writeFileSync(graphPath, Buffer.concat([graphBytes, Buffer.from(" ")]));
    result = await runGeneratedArtifactGate(fixture);
    assert.equal(result.status, "generated_artifact_mismatch");
    assert.ok(
      result.status === "generated_artifact_mismatch" &&
        result.artifacts.some((entry) => entry.artifact === "topology")
    );
    writeFileSync(graphPath, graphBytes);
  });

  await test("self-consistent compiler-divergent topology fails derivation", async () => {
    const topology = readWorkspaceCodeTopologyFiles(fixture);
    assert.equal(topology.status, "complete");
    if (topology.status !== "complete") return;
    const parsed = parseCodeTopologyArtifact(topology.files);
    assert.equal(parsed.status, "complete");
    if (parsed.status !== "complete") return;
    const divergent = structuredClone(parsed.artifact);
    divergent.files[0]!.source_hash = "0".repeat(64);
    divergent.projection_digest = codeTopologyArtifactProjectionDigest({
      files: divergent.files,
      symbols: divergent.symbols,
      edges: divergent.edges,
      frontiers: divergent.frontiers,
    });
    const serialized = serializeCodeTopologyArtifact(divergent);
    const topologyRoot = resolve(fixture, ".tieline/topology");
    rmSync(topologyRoot, { recursive: true, force: true });
    for (const [name, bytes] of serialized.files) {
      const path = resolve(topologyRoot, name);
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, bytes);
    }
    assert.equal(
      await runCodeTopologyArtifactCommand(
        "validate",
        { repository: fixture, json: true },
        commandIo
      ),
      0,
      "parser-free structural and freshness validation accepts the self-consistent artifact"
    );
    const result = await runGeneratedArtifactGate(fixture);
    assert.equal(result.status, "generated_artifact_mismatch");
    assert.ok(
      result.status === "generated_artifact_mismatch" &&
        result.artifacts.some((entry) => entry.artifact === "topology")
    );
  });
} finally {
  rmSync(root, { recursive: true, force: true });
}

report();
